project_id = "kovjaodhpnnmtrtbrwnf"

[functions.ai-analysis]
verify_jwt = false

[functions.analyze-lead-screenshots]
verify_jwt = false

[functions.ensure-mentorado]
verify_jwt = false

[functions.sos-triage]
verify_jwt = false

[functions.ai-tools]
verify_jwt = false
